# 8080포트 변경
server:
  port: 47788

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://3.39.72.120:9876/post
    url: jdbc:mysql://localhost:3306/post
    username: root
#    password: 1234
    password: doseong9114!!
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
logging:
  level:
    root: info
    com.example: debug
    org.hibernate.SQL: debug

